### PR TITLE
added typescript declarations to module, as well as accompanying tests

### PR DESCRIPTION
**Pull request by aaronleopold**
Here you go!! While I use TypeScript a lot more frequently these days, this was my first time adding TypeScript support in a JavaScript library! So if I missed anything please let me know and I'll go ahead and correct it! 

In order to properly use this module with TypeScript, and properly test it, a few new development dependencies were added:

```json
"@types/expect": "^24.3.0",
"@types/express": "^4.17.8",
"@types/mocha": "^8.0.3",
"@types/supertest": "^2.0.10",
"ts-mocha": "^7.0.0",
"typescript": "^4.0.3"
```

To run the mocha tests in TypeScript, a new script was added to the `package.json`. The procedure is as follows:

```bash
npm install
npm run test-ts
```
I made an important comment in the `test/index.ts` file that I will also paste here:

"Please note: there are type errors all throughout this document. This is because these tests were largely copied over from the JavaScript version to test the baseline functionality. While the type errors exist, they do not affect the test outcomes. This may effect the CI badge on GitHub, however. Honestly not sure about that.

Additionally, some of the type errors result in the lack of types installed for certain dependencies. This was intentionally left out, because I did not want to overly inflate the package.json with new packages.  I didn't want to make any assumptions, basically. If the owner of this project decides they want to tack on the additional types to remove the type errors then that's great"

If you want me to correct these type errors let me know and I'd be happy to install the packages to remove some, but keep in mind a lot of the tests themselves invoke type errors just by the nature of the test (e.g. testing null parameter when the arg is enforced to be a custom type).

(last thing I promise! I know this is already a small novel) I also noticed you have another library with a TypeScript issue. If you want me to work on that one as well just let me know and I'll be happy to do it :)

### CODE REVIEW

**Comment by aaronleopold** [comment]
I also noticed one of the workflow tests failed, I've never personally used workflows and am unsure of what is causing it but I'd be happy to correct it if you would be able to give me some insight into what its failing from

**Review by Cherry — APPROVED** [review]
This looks fantastic, thanks @aaronleopold!

I'm not familiar with TypeScript enough, but what dependencies would be required to make the `test/index.ts` file properly typed everywhere?

The workflow failure here is entirely on my end - there's a misconfiguration with the code coverage report, so don't worry about that.

**Comment by Cherry** [comment]
Also, looking at https://www.npmjs.com/package/@types/expect, it seems like this package isn't necessary and `expect` exports its own types now? Could we use those to prevent the deprecation warning when installing?
```npm WARN deprecated @types/expect@24.3.0: This is a stub types definition. expect provides its own type definitions, so you do not need this installed.```

**Comment by aaronleopold** [comment]
So as far as dependencies go I can take a look shortly when I get back home to remember what typings it was yelling at me for. The other type errors were just a result of some of the tests themselves since they try to pass in an incorrectly typed options object

**Comment by Cherry** [comment]
Thanks for the insight @aaronleopold. Let me know if there's any other questions on your end, else I'd be happy to merge this once we've solidified what `types` are necessary.

**Comment by aaronleopold** [comment]
Okay, so it seems like it just wanted the types for mocha. I went ahead and added those, but you'll still have the type errors for some of the tests from what I talked about previously (e.g. null is not the same type as the OptionConfig type that I made, etc etc). To remove all the type errors it would really mean altering the tests that pass an invalid option, but keeping the tests where the type is correct but the specific value may be wrong. For example, the test that "fails when `failure_fraction` has a bad value".

I'll send another push to this PR shortly!

**Review by Cherry — APPROVED** [review]
Great stuff, thanks @aaronleopold. I'll do my best to keep the TypeScript support up to date for any future releases!

**Comment by Hongbo-Miao** [comment]
This approach will have two copies.
When @Cherry you are comfortable with TypeScript in future, then it can only have one TypeScript copy left, while JavaScript can be the generated version : )

**Pull request merged**
